### ISSUE TITLE
funcs_phy-assoc_fig5b.R

### ISSUE THREAD

**Issue by ucassee** [Finn-Lab/MGS-gut#5]
Deer developer，
       I am trying to analysis GO functions abundance  with my data. So I try to run your scripts(funcs_phy-assoc_fig5b.R) first and wish to follow. But I can't install R packages(CoDaSeq)  and don't find the `taxonomy_all.tab` file in your ftp.  Could you please offer some help for me to follow?

Thanks in advance~

**Comment by alexmsalmeida** [comment]
Hi,

The taxonomy_all.tab is just a merged version of the taxonomy_hgr.tab and taxonomy_umgs.tab files. I have updated the script so you can give both files separately.

Not sure I can help you with the CoDaSeq installation. I would advise you to check their github page: https://github.com/ggloor/CoDaSeq and raise an issue there. I remember that in my experience I had a couple of issues installing the latest CoDaSeq version due to rjags. This was because I was missing JAGs on Mac OSX (I had to install it manually using, for instance, brew install jags). However, for that particular script you can actually just load ALDEx2 without CoDaSeq.

Alex

**Comment by ucassee** [comment]
It works now. Thanks for your reply~
